### ISSUE TITLE
Elite Mode issues

### ISSUE THREAD

**Issue by somerandomfellow** [Menardi/whosthatpokemon#14]
Meltan and Melmetal cries do not play, and when practicing with exclusively Gen 8 it stops after 42 cries played.

(also, I'm not sure if you're aware but the cries currently in are cut off)

**Comment by Menardi** [comment]
Apologies for the long delay in replying to this, I haven't checked the Issues on here in some time. This should be fixed with the addition of new cries in https://github.com/Menardi/whosthatpokemon/pull/16. Let me know if you continue to have issues after this.

**Comment by sora10pls** [comment]
This problem does still persist as of the latest commit, only half of the current pool of potential Pokémon (rounded up, if necessary) is played.

Generation VIII Elite Mode should have 91 Cries, but only 46 play.
![image](https://user-images.githubusercontent.com/17801814/102034364-d9472900-3d8b-11eb-8476-ee9a2698ec6f.png)

**Comment by Menardi** [comment]
Ah! In that case I will re-open it and investigate later this week. Thanks for letting me know!

**Comment by Menardi** [comment]
This is now fixed. Thanks for the report!
